src/objects/Bitcoin_Calculation__e.object
<CustomObject>
    <fields>
        <fullName>Data__c</fullName>
        <label>Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Bitcoin Calculation</label>
    <pluralLabel>Bitcoin Calculations</pluralLabel>
</CustomObject>

src/objects/Bitcoin_Price__c.object
<CustomObject>
    <fields>
        <fullName>High__c</fullName>
        <label>High</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Low__c</fullName>
        <label>Low</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>Bitcoin Price</label>
    <nameField>
        <displayFormat>BTC-{0000000}</displayFormat>
        <label>Bitcoin Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bitcoin Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/QueryBitcoinBatch.cls
public class QueryBitcoinBatch implements Database.Batchable<sObject>, Database.Stateful {
    
    public List<Bitcoin_Price__c> allScope;
    
    public QueryBitcoinBatch(){
        allScope = new List<Bitcoin_Price__c>();
    }    
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        String query = 
            'SELECT Id, High__c, Low__c FROM Bitcoin_Price__c WHERE Low__c >= 1782.3000 AND Low__c <= 1782.4000';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Bitcoin_Price__c> scope){
        allScope.addAll(scope);
    }
    
    public void finish(Database.BatchableContext BC){
        Map<String, Object> retObj = new Map<String, Object>{'jobId' => (BC.getJobId()+'').left(15), 'allScope' => allScope};
        Eventbus.publish(new Bitcoin_Calculation__e(Data__c=JSON.serialize(retObj)));
    }
}