src/objects/Bitcoin_Price__c.object
<CustomObject>
    <fields>
        <fullName>Close__c</fullName>
        <label>Close</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>High__c</fullName>
        <label>High</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Low__c</fullName>
        <label>Low</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open__c</fullName>
        <label>Open</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <label>Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Timestamp__c</fullName>
        <externalId>true</externalId>
        <label>Timestamp</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Volume_BTC__c</fullName>
        <label>Volume BTC</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Volume_Currency__c</fullName>
        <label>Volume Currency</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Weighted_Price__c</fullName>
        <label>Weighted Price</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <label>Bitcoin Price</label>
    <nameField>
        <displayFormat>BTC-{0000000}</displayFormat>
        <label>Bitcoin Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bitcoin Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Bitcoin_Price_Big__b.object
<CustomObject>
    <fields>
        <fullName>Close__c</fullName>
        <label>Close</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>High__c</fullName>
        <label>High</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Low__c</fullName>
        <label>Low</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open__c</fullName>
        <label>Open</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <label>Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Timestamp__c</fullName>
        <label>Timestamp</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Volume_BTC__c</fullName>
        <label>Volume BTC</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Volume_Currency__c</fullName>
        <label>Volume Currency</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Weighted_Price__c</fullName>
        <label>Weighted Price</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <label>Bitcoin Price Big</label>
    <pluralLabel>Bitcoin Prices Big</pluralLabel>
</CustomObject>

src/classes/PopulateBitcoinBatch.cls
public class PopulateBitcoinBatch implements Database.Batchable<sObject>{
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        String query = 
        'SELECT Id, Close__c, High__c, Low__c, Open__c, Time__c, Timestamp__c, Volume_BTC__c, Volume_Currency__c, Weighted_Price__c ' +
        'FROM Bitcoin_Price__c ORDER BY Time__c DESC';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Bitcoin_Price__c> scope){
		List<Bitcoin_Price_Big__b> bigs = new List<Bitcoin_Price_Big__b>();
        for(Bitcoin_Price__c b : scope) {
            bigs.add(
                new Bitcoin_Price_Big__b(
            		Close__c = b.Close__c,
                    High__c = b.High__c,
                    Low__c = b.Low__c,
                    Open__c = b.Open__c,
                    Time__c = b.Time__c,
                    Timestamp__c = b.Timestamp__c,
                    Volume_BTC__c = b.Volume_BTC__c,
                    Volume_Currency__c = b.Volume_Currency__c,
                    Weighted_Price__c = b.Weighted_Price__c
            	)
            );
        }
		database.insertImmediate(bigs);            
    }
    
    public void finish(Database.BatchableContext BC){
    }
}